[package]
name = "centau/ecr"
description = "An ECS library for Luau."
version = "0.9.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "LICENSE.md", "default.project.json"]
exclude = ["CHANGELOG.md", ".gitignore", ".github", ".gitattributes", "test", "docs", "README.md", ".luaurc"]

[dependencies]
